# docker build -f Dockerfile.dev -t railgun_dev .
# docker run -it --rm -v `pwd`:/root/railgun -p 3000:3000 railgun_dev
# rails s -p 3000 -b '0.0.0.0'

FROM railgun

WORKDIR /root/railgun

ADD . /root/railgun

RUN rbenv exec bundle install

CMD service postgresql start \
    && rbenv exec bundle exec guard \
    && /bin/bash
