# docker build -f Dockerfile.prod -t railgun_prod .
# docker run -i -t -p 3000:3000 railgun_prod

FROM railgun

WORKDIR /root/railgun

RUN git pull origin master

RUN cp .env.example .env
RUN rbenv exec bundle install

ENV RAILS_ENV=production

ENTRYPOINT ["rbenv", "exec", "bundle", "exec", "rails", "server", "-p", "3000", "-b", "0.0.0.0"]
